meta:
  environment: ~
  nfs_server:
    address: (( jobs.nfs_z1.networks.nfs1.static_ips.[0] || nil ))
    allow_from_entries:
      - (( .networks.nfs1.subnets.[0].range || nil ))
    share: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: nfs_z1
    templates:
    - name: debian_nfs_server
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties:
      nfs_server: (( meta.nfs_server ))

networks: (( merge ))

properties: {}
