---
jobs:
- name: prod
  public: true
  serial: true
  plan:
  - aggregate:
    - get: deployments
    - get: nfs-release
    - get: nfs
      passed: [ dev ]
  - task: vsphere-stemcell
    file: nfs/ci/download.yml
    config:
      params: (( grab config.vsphere_stemcell_download_params ))
  - task: spruce-merge
    file: nfs/ci/spruce-merge.yml
    config:
      params:
        files: deployments/prod/nfs/templates/manifest.yml deployments/prod/nfs/stub.yml
  - put: prod-deployment
    params:
      manifest: spruce-merge/manifest.yml
      releases:
      - nfs-release/*.tgz
      stemcells:
      - vsphere-stemcell/*.tgz

resources:
- name: prod-deployment
  type: bosh-deployment
  source:
    target: (( param "Set bosh target for nfs deployment" ))
    username: (( param "Set bosh username for nfs deployment" ))
    password: (( param "Set bosh password for nfs deployment" ))
    deployment: (( param "Set deployment name" ))
